--------------------------------------
-- IO device identifier
--------------------------------------
IO_KEYBOARD_SDL2_IDENTIFIER = "keyboard-sdl2"

--------------------------------------
-- Digital input states
--------------------------------------

IO_KEYBOARD_SDL2_DI_UNASSIGNED = 0x00
IO_KEYBOARD_SDL2_DI_ESCAPE = 0x01
IO_KEYBOARD_SDL2_DI_1 = 0x02
IO_KEYBOARD_SDL2_DI_2 = 0x03
IO_KEYBOARD_SDL2_DI_3 = 0x04
IO_KEYBOARD_SDL2_DI_4 = 0x05
IO_KEYBOARD_SDL2_DI_5 = 0x06
IO_KEYBOARD_SDL2_DI_6 = 0x07
IO_KEYBOARD_SDL2_DI_7 = 0x08
IO_KEYBOARD_SDL2_DI_8 = 0x09
IO_KEYBOARD_SDL2_DI_9 = 0x0A
IO_KEYBOARD_SDL2_DI_0 = 0x0B
-- - on main keyboard
IO_KEYBOARD_SDL2_DI_MINUS = 0x0C
IO_KEYBOARD_SDL2_DI_EQUALS = 0x0D
-- backspace
IO_KEYBOARD_SDL2_DI_BACK = 0x0E
IO_KEYBOARD_SDL2_DI_TAB = 0x0F
IO_KEYBOARD_SDL2_DI_Q = 0x10
IO_KEYBOARD_SDL2_DI_W = 0x11
IO_KEYBOARD_SDL2_DI_E = 0x12
IO_KEYBOARD_SDL2_DI_R = 0x13
IO_KEYBOARD_SDL2_DI_T = 0x14
IO_KEYBOARD_SDL2_DI_Y = 0x15
IO_KEYBOARD_SDL2_DI_U = 0x16
IO_KEYBOARD_SDL2_DI_I = 0x17
IO_KEYBOARD_SDL2_DI_O = 0x18
IO_KEYBOARD_SDL2_DI_P = 0x19
IO_KEYBOARD_SDL2_DI_LBRACKET = 0x1A
IO_KEYBOARD_SDL2_DI_RBRACKET = 0x1B
-- enter on main keyboard
IO_KEYBOARD_SDL2_DI_RETURN = 0x1C
IO_KEYBOARD_SDL2_DI_LCONTROL = 0x1D
IO_KEYBOARD_SDL2_DI_A = 0x1E
IO_KEYBOARD_SDL2_DI_S = 0x1F
IO_KEYBOARD_SDL2_DI_D = 0x20
IO_KEYBOARD_SDL2_DI_F = 0x21
IO_KEYBOARD_SDL2_DI_G = 0x22
IO_KEYBOARD_SDL2_DI_H = 0x23
IO_KEYBOARD_SDL2_DI_J = 0x24
IO_KEYBOARD_SDL2_DI_K = 0x25
IO_KEYBOARD_SDL2_DI_L = 0x26
IO_KEYBOARD_SDL2_DI_SEMICOLON = 0x27
IO_KEYBOARD_SDL2_DI_APOSTROPHE = 0x28
-- accent
IO_KEYBOARD_SDL2_DI_GRAVE = 0x29
IO_KEYBOARD_SDL2_DI_LSHIFT = 0x2A
IO_KEYBOARD_SDL2_DI_BACKSLASH = 0x2B
IO_KEYBOARD_SDL2_DI_Z = 0x2C
IO_KEYBOARD_SDL2_DI_X = 0x2D
IO_KEYBOARD_SDL2_DI_C = 0x2E
IO_KEYBOARD_SDL2_DI_V = 0x2F
IO_KEYBOARD_SDL2_DI_B = 0x30
IO_KEYBOARD_SDL2_DI_N = 0x31
IO_KEYBOARD_SDL2_DI_M = 0x32
IO_KEYBOARD_SDL2_DI_COMMA = 0x33
-- . on main keyboard
IO_KEYBOARD_SDL2_DI_PERIOD = 0x34
-- / on main keyboard
IO_KEYBOARD_SDL2_DI_SLASH = 0x35
IO_KEYBOARD_SDL2_DI_RSHIFT = 0x36
-- * on numeric keypad
IO_KEYBOARD_SDL2_DI_MULTIPLY = 0x37
-- left Alt
IO_KEYBOARD_SDL2_DI_LMENU = 0x38
IO_KEYBOARD_SDL2_DI_SPACE = 0x39
IO_KEYBOARD_SDL2_DI_CAPITAL = 0x3A
IO_KEYBOARD_SDL2_DI_F1 = 0x3B
IO_KEYBOARD_SDL2_DI_F2 = 0x3C
IO_KEYBOARD_SDL2_DI_F3 = 0x3D
IO_KEYBOARD_SDL2_DI_F4 = 0x3E
IO_KEYBOARD_SDL2_DI_F5 = 0x3F
IO_KEYBOARD_SDL2_DI_F6 = 0x40
IO_KEYBOARD_SDL2_DI_F7 = 0x41
IO_KEYBOARD_SDL2_DI_F8 = 0x42
IO_KEYBOARD_SDL2_DI_F9 = 0x43
IO_KEYBOARD_SDL2_DI_F10 = 0x44
IO_KEYBOARD_SDL2_DI_NUMLOCK = 0x45
-- Scroll Lock
IO_KEYBOARD_SDL2_DI_SCROLL = 0x46
IO_KEYBOARD_SDL2_DI_NUMPAD7 = 0x47
IO_KEYBOARD_SDL2_DI_NUMPAD8 = 0x48
IO_KEYBOARD_SDL2_DI_NUMPAD9 = 0x49
-- - on numeric keypad
IO_KEYBOARD_SDL2_DI_SUBTRACT = 0x4A
IO_KEYBOARD_SDL2_DI_NUMPAD4 = 0x4B
IO_KEYBOARD_SDL2_DI_NUMPAD5 = 0x4C
IO_KEYBOARD_SDL2_DI_NUMPAD6 = 0x4D
-- + on numeric keypad
IO_KEYBOARD_SDL2_DI_ADD = 0x4E
IO_KEYBOARD_SDL2_DI_NUMPAD1 = 0x4F
IO_KEYBOARD_SDL2_DI_NUMPAD2 = 0x50
IO_KEYBOARD_SDL2_DI_NUMPAD3 = 0x51
IO_KEYBOARD_SDL2_DI_NUMPAD0 = 0x52
-- . on numeric keypad
IO_KEYBOARD_SDL2_DI_DECIMAL = 0x53
-- < > | on UK/Germany keyboards
IO_KEYBOARD_SDL2_DI_OEM102 = 0x56
IO_KEYBOARD_SDL2_DI_F11 = 0x57
IO_KEYBOARD_SDL2_DI_F12 = 0x58
-- (NEC PC98)
IO_KEYBOARD_SDL2_DI_F13 = 0x64
-- (NEC PC98)
IO_KEYBOARD_SDL2_DI_F14 = 0x65
-- (NEC PC98)
IO_KEYBOARD_SDL2_DI_F15 = 0x66
-- (Japanese keyboard)
IO_KEYBOARD_SDL2_DI_KANA = 0x70
-- / ? on Portugese (Brazilian) keyboards
IO_KEYBOARD_SDL2_DI_ABNTC1 = 0x73
-- (Japanese keyboard)
IO_KEYBOARD_SDL2_DI_CONVERT = 0x79
-- (Japanese keyboard)
IO_KEYBOARD_SDL2_DI_NOCONVERT = 0x7B
-- (Japanese keyboard)
IO_KEYBOARD_SDL2_DI_YEN = 0x7D
-- NUMPAD . on Portugese (Brazilian) keyboards
IO_KEYBOARD_SDL2_DI_ABNTC2 = 0x7E
-- = on numeric keypad (NEC PC98)
IO_KEYBOARD_SDL2_DI_NUMPADEQUALS = 0x8D
-- Previous Track (IO_KEYBOARD_SDL2_DI_CIRCUMFLEX on Japanese keyboard)
IO_KEYBOARD_SDL2_DI_PREVTRACK = 0x90
-- (NEC PC98)
IO_KEYBOARD_SDL2_DI_AT = 0x91
-- (NEC PC98)
IO_KEYBOARD_SDL2_DI_COLON = 0x92
-- (NEC PC98)
IO_KEYBOARD_SDL2_DI_UNDERLINE = 0x93
-- (Japanese keyboard)
IO_KEYBOARD_SDL2_DI_KANJI = 0x94
-- (NEC PC98)
IO_KEYBOARD_SDL2_DI_STOP = 0x95
-- (Japan AX)
IO_KEYBOARD_SDL2_DI_AX = 0x96
-- (J3100)
IO_KEYBOARD_SDL2_DI_UNLABELED = 0x97
-- Next Track
IO_KEYBOARD_SDL2_DI_NEXTRACK = 0x99
-- Enter on numeric keypad
IO_KEYBOARD_SDL2_DI_NUMPADENTER = 0x9C
IO_KEYBOARD_SDL2_DI_RCONTROL = 0x9D
-- Mute
IO_KEYBOARD_SDL2_DI_MUTE = 0xA0
-- Calculator
IO_KEYBOARD_SDL2_DI_CALCULATOR = 0xA1
-- Play / Pause
IO_KEYBOARD_SDL2_DI_PLAYPAUSE = 0xA2
-- Media Stop
IO_KEYBOARD_SDL2_DI_MEDIASTOP = 0xA4
-- Volume -
IO_KEYBOARD_SDL2_DI_VOLUMEDOWN = 0xAE
-- Volume +
IO_KEYBOARD_SDL2_DI_VOLUMEUP = 0xB0
-- Web home
IO_KEYBOARD_SDL2_DI_WEBHOME = 0xB2
-- , on numeric keypad (NEC PC98)
IO_KEYBOARD_SDL2_DI_NUMPADCOMMA = 0xB3
-- / on numeric keypad
IO_KEYBOARD_SDL2_DI_DIVIDE = 0xB5
IO_KEYBOARD_SDL2_DI_SYSRQ = 0xB7
-- right Alt
IO_KEYBOARD_SDL2_DI_RMENU = 0xB8
-- Pause
IO_KEYBOARD_SDL2_DI_PAUSE = 0xC5
-- Home on arrow keypad
IO_KEYBOARD_SDL2_DI_HOME = 0xC7
-- UpArrow on arrow keypad
IO_KEYBOARD_SDL2_DI_UP = 0xC8
-- PgUp on arrow keypad
IO_KEYBOARD_SDL2_DI_PGUP = 0xC9
-- LeftArrow on arrow keypad
IO_KEYBOARD_SDL2_DI_LEFT = 0xCB
-- RightArrow on arrow keypad
IO_KEYBOARD_SDL2_DI_RIGHT = 0xCD
-- End on arrow keypad
IO_KEYBOARD_SDL2_DI_END = 0xCF
-- DownArrow on arrow keypad
IO_KEYBOARD_SDL2_DI_DOWN = 0xD0
-- PgDn on arrow keypad
IO_KEYBOARD_SDL2_DI_PGDOWN = 0xD1
-- Insert on arrow keypad
IO_KEYBOARD_SDL2_DI_INSERT = 0xD2
-- Delete on arrow keypad
IO_KEYBOARD_SDL2_DI_DELETE = 0xD3
-- Left Windows key
IO_KEYBOARD_SDL2_DI_LWIN = 0xDB
-- Right Windows key
IO_KEYBOARD_SDL2_DI_RWIN = 0xDC
-- AppMenu key
IO_KEYBOARD_SDL2_DI_APPS = 0xDD
-- System Power
IO_KEYBOARD_SDL2_DI_POWER = 0xDE
-- System Sleep
IO_KEYBOARD_SDL2_DI_SLEEP = 0xDF
-- System Wake
IO_KEYBOARD_SDL2_DI_WAKE = 0xE3
-- Web Search
IO_KEYBOARD_SDL2_DI_WEBSEARCH = 0xE5
-- Web Favorites
IO_KEYBOARD_SDL2_DI_WEBFAVORITES = 0xE6
-- Web Refresh
IO_KEYBOARD_SDL2_DI_WEBREFRESH = 0xE7
-- Web Stop
IO_KEYBOARD_SDL2_DI_WEBSTOP = 0xE8
-- Web Forward
IO_KEYBOARD_SDL2_DI_WEBFORWARD = 0xE9
-- Web Back
IO_KEYBOARD_SDL2_DI_WEBBACK = 0xEA
-- My Computer
IO_KEYBOARD_SDL2_DI_MYCOMPUTER = 0xEB
-- Mail
IO_KEYBOARD_SDL2_DI_MAIL = 0xEC
-- Media Select
IO_KEYBOARD_SDL2_DI_MEDIASELECT = 0xED
