--------------------------------------
-- IO device identifier
--------------------------------------
IO_IIDXIO_IDENTIFIER = "iidxio"

--------------------------------------
-- Analog input states
--------------------------------------
IO_IIDXIO_AI_TT_P1 = 0
IO_IIDXIO_AI_TT_P2 = 1
IO_IIDXIO_AI_SLIDER_1 = 2
IO_IIDXIO_AI_SLIDER_2 = 3
IO_IIDXIO_AI_SLIDER_3 = 4
IO_IIDXIO_AI_SLIDER_4 = 5
IO_IIDXIO_AI_SLIDER_5 = 6

--------------------------------------
-- Digital input states
--------------------------------------
IO_IIDXIO_DI_P1_KEY1 = 0
IO_IIDXIO_DI_P1_KEY2 = 1
IO_IIDXIO_DI_P1_KEY3 = 2
IO_IIDXIO_DI_P1_KEY4 = 3
IO_IIDXIO_DI_P1_KEY5 = 4
IO_IIDXIO_DI_P1_KEY6 = 5
IO_IIDXIO_DI_P1_KEY7 = 6

IO_IIDXIO_DI_P2_KEY1 = 7
IO_IIDXIO_DI_P2_KEY2 = 8
IO_IIDXIO_DI_P2_KEY3 = 9
IO_IIDXIO_DI_P2_KEY4 = 10
IO_IIDXIO_DI_P2_KEY5 = 11
IO_IIDXIO_DI_P2_KEY6 = 12
IO_IIDXIO_DI_P2_KEY7 = 13

IO_IIDXIO_DI_14KEY_ANY = 14
IO_IIDXIO_DI_P1KEY_ANY = 15
IO_IIDXIO_DI_P2KEY_ANY = 16

IO_IIDXIO_DI_P1_START = 17
IO_IIDXIO_DI_P2_START = 18
IO_IIDXIO_DI_VEFX = 19
IO_IIDXIO_DI_EFFECTOR = 20
IO_IIDXIO_DI_TEST = 21
IO_IIDXIO_DI_SERVICE = 22

--------------------------------------
-- Digital output states
--------------------------------------
IO_IIDXIO_DO_P1_KEY1 = 0
IO_IIDXIO_DO_P1_KEY2 = 1
IO_IIDXIO_DO_P1_KEY3 = 2
IO_IIDXIO_DO_P1_KEY4 = 3
IO_IIDXIO_DO_P1_KEY5 = 4
IO_IIDXIO_DO_P1_KEY6 = 5
IO_IIDXIO_DO_P1_KEY7 = 6

IO_IIDXIO_DO_P2_KEY1 = 7
IO_IIDXIO_DO_P2_KEY2 = 8
IO_IIDXIO_DO_P2_KEY3 = 9
IO_IIDXIO_DO_P2_KEY4 = 10
IO_IIDXIO_DO_P2_KEY5 = 11
IO_IIDXIO_DO_P2_KEY6 = 12
IO_IIDXIO_DO_P2_KEY7 = 13

IO_IIDXIO_DO_P1_START = 14
IO_IIDXIO_DO_P2_START = 15
IO_IIDXIO_DO_VEFX = 16
IO_IIDXIO_DO_EFFECTOR = 17

IO_IIDXIO_DO_HALO_LEFT_RED = 18
IO_IIDXIO_DO_HALO_LEFT_YELLOW = 19
IO_IIDXIO_DO_HALO_LEFT_GREEN = 20
IO_IIDXIO_DO_HALO_LEFT_BLUE = 21
IO_IIDXIO_DO_HALO_RIGHT_BLUE = 22
IO_IIDXIO_DO_HALO_RIGHT_GREEN = 23
IO_IIDXIO_DO_HALO_RIGHT_YELLOW = 24
IO_IIDXIO_DO_HALO_RIGHT_RED = 25

IO_IIDXIO_DO_NEONS = 26

--------------------------------------
-- Text output states
--------------------------------------
IO_IIDX_FX_TO_16SEG = 0
