--------------------------------------
-- IO device identifier
--------------------------------------
IO_PIULXIO_IDENTIFIER = "piulxio"

--------------------------------------
-- Digital input states
--------------------------------------
-- Panels P1 (if any sensor pressed)
IO_PIUIOLXIO_DI_P1_LU = 0
IO_PIUIOLXIO_DI_P1_RU = 5
IO_PIUIOLXIO_DI_P1_CN = 10
IO_PIUIOLXIO_DI_P1_LD = 15
IO_PIUIOLXIO_DI_P1_RD = 20

-- Panels P2 (if any sensor pressed)
IO_PIUIOLXIO_DI_P2_LU = 25
IO_PIUIOLXIO_DI_P2_RU = 30
IO_PIUIOLXIO_DI_P2_CN = 35
IO_PIUIOLXIO_DI_P2_LD = 40
IO_PIUIOLXIO_DI_P2_RD = 45

-- Menu Buttons P1
IO_PIUIOLXIO_DI_P1_LU_MENU = 54
IO_PIUIOLXIO_DI_P1_RU_MENU = 55
IO_PIUIOLXIO_DI_P1_CN_MENU = 56
IO_PIUIOLXIO_DI_P1_LD_MENU = 57
IO_PIUIOLXIO_DI_P1_RD_MENU = 58

-- Menu Buttons P2
IO_PIUIOLXIO_DI_P2_LU_MENU = 59
IO_PIUIOLXIO_DI_P2_RU_MENU = 60
IO_PIUIOLXIO_DI_P2_CN_MENU = 61
IO_PIUIOLXIO_DI_P2_LD_MENU = 62
IO_PIUIOLXIO_DI_P2_RD_MENU = 63

-- Operator inputs
IO_PIUIOLXIO_DI_OP_TEST = 50
IO_PIUIOLXIO_DI_OP_SERVICE = 51
IO_PIUIOLXIO_DI_OP_CLEAR = 52
IO_PIUIOLXIO_DI_OP_COIN = 53

-- Single sensor states P1
IO_PIUIOLXIO_DI_P1_LU_SENS0 = 1
IO_PIUIOLXIO_DI_P1_LU_SENS1 = 2
IO_PIUIOLXIO_DI_P1_LU_SENS2 = 3
IO_PIUIOLXIO_DI_P1_LU_SENS3 = 4

IO_PIUIOLXIO_DI_P1_RU_SENS0 = 6
IO_PIUIOLXIO_DI_P1_RU_SENS1 = 7
IO_PIUIOLXIO_DI_P1_RU_SENS2 = 8
IO_PIUIOLXIO_DI_P1_RU_SENS3 = 9

IO_PIUIOLXIO_DI_P1_CN_SENS0 = 11
IO_PIUIOLXIO_DI_P1_CN_SENS1 = 12
IO_PIUIOLXIO_DI_P1_CN_SENS2 = 13
IO_PIUIOLXIO_DI_P1_CN_SENS3 = 14

IO_PIUIOLXIO_DI_P1_LD_SENS0 = 16
IO_PIUIOLXIO_DI_P1_LD_SENS1 = 17
IO_PIUIOLXIO_DI_P1_LD_SENS2 = 18
IO_PIUIOLXIO_DI_P1_LD_SENS3 = 19

IO_PIUIOLXIO_DI_P1_RD_SENS0 = 21
IO_PIUIOLXIO_DI_P1_RD_SENS1 = 22
IO_PIUIOLXIO_DI_P1_RD_SENS2 = 23
IO_PIUIOLXIO_DI_P1_RD_SENS3 = 24

-- Single sensor states P2
IO_PIUIOLXIO_DI_P2_LU_SENS0 = 26
IO_PIUIOLXIO_DI_P2_LU_SENS1 = 27
IO_PIUIOLXIO_DI_P2_LU_SENS2 = 28
IO_PIUIOLXIO_DI_P2_LU_SENS3 = 29

IO_PIUIOLXIO_DI_P2_RU_SENS0 = 31
IO_PIUIOLXIO_DI_P2_RU_SENS1 = 32
IO_PIUIOLXIO_DI_P2_RU_SENS2 = 33
IO_PIUIOLXIO_DI_P2_RU_SENS3 = 34

IO_PIUIOLXIO_DI_P2_CN_SENS0 = 36
IO_PIUIOLXIO_DI_P2_CN_SENS1 = 37
IO_PIUIOLXIO_DI_P2_CN_SENS2 = 38
IO_PIUIOLXIO_DI_P2_CN_SENS3 = 39

IO_PIUIOLXIO_DI_P2_LD_SENS0 = 41
IO_PIUIOLXIO_DI_P2_LD_SENS1 = 42
IO_PIUIOLXIO_DI_P2_LD_SENS2 = 43
IO_PIUIOLXIO_DI_P2_LD_SENS3 = 44

IO_PIUIOLXIO_DI_P2_RD_SENS0 = 46
IO_PIUIOLXIO_DI_P2_RD_SENS1 = 47
IO_PIUIOLXIO_DI_P2_RD_SENS2 = 48
IO_PIUIOLXIO_DI_P2_RD_SENS3 = 49

--------------------------------------
-- Digital output states
--------------------------------------
IO_PIUIOLXIO_DO_P1_LU = 0
IO_PIUIOLXIO_DO_P1_RU = 1
IO_PIUIOLXIO_DO_P1_CN = 2
IO_PIUIOLXIO_DO_P1_LD = 3
IO_PIUIOLXIO_DO_P1_RD = 4

IO_PIUIOLXIO_DO_P2_LU = 5
IO_PIUIOLXIO_DO_P2_RU = 6
IO_PIUIOLXIO_DO_P2_CN = 7
IO_PIUIOLXIO_DO_P2_LD = 8
IO_PIUIOLXIO_DO_P2_RD = 9

IO_PIUIOLXIO_DO_BASS = 10
IO_PIUIOLXIO_DO_HALOR2 = 11
IO_PIUIOLXIO_DO_HALOR1 = 12
IO_PIUIOLXIO_DO_HALOL2 = 13
IO_PIUIOLXIO_DO_HALOL1 = 14

IO_PIUIOLXIO_DO_COINCOUNTER = 15
IO_PIUIOLXIO_DO_COINCOUNTER2 = 16

IO_PIUIOLXIO_DO_P1_LU_MENU = 17
IO_PIUIOLXIO_DO_P1_RU_MENU = 18
IO_PIUIOLXIO_DO_P1_CN_MENU = 19
IO_PIUIOLXIO_DO_P1_LD_MENU = 20
IO_PIUIOLXIO_DO_P1_RD_MENU = 21

IO_PIUIOLXIO_DO_P2_LU_MENU = 22
IO_PIUIOLXIO_DO_P2_RU_MENU = 23
IO_PIUIOLXIO_DO_P2_CN_MENU = 24
IO_PIUIOLXIO_DO_P2_LD_MENU = 25
IO_PIUIOLXIO_DO_P2_RD_MENU = 26